project:
  type: book

book:
  title: "R and Shiny Frameworks"
  author: "Harvey Lieberman"
  date: "12/21/2023"
  chapters:
    - index.qmd
    - introduction.qmd
    - importing_data.qmd
    - data_wrangling.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



