project:
  type: book

book:
  title: "R and Shiny Frameworks"
  author: "Harvey Lieberman"
  date: "12/21/2023"
  chapters:
    - index.qmd
    - introduction.qmd
    - instructions.qmd
    - importing_data.qmd
    - data_wrangling.qmd
    - advanced_instructions.qmd
    - shiny_interface.qmd
    - shiny_reactivity.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

